### ISSUE TITLE
build support for Ubuntu Jammy

### ISSUE THREAD

**Issue by kgilmer** [jovanlanik/gtklock#54]
I'm have build your project using `make && make install` on Ubuntu 22.10 without problem.  However when I try to build on Ubuntu 22.04, somehow the include paths are not making it to the compiler invocation.  Any idea what I may be missing?

Ubuntu 22.10:
```
$ make
...
cc -std=c11 -Iinclude -DPREFIX=/usr -I/usr/include/security -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-layer-shell -pthread  -DMAJOR_VERSION=2 -DMINOR_VERSION=0 -DMICRO_VERSION=0   -c -o src/auth.o src/auth.c
...
```

Ubuntu 22.04:
```
$ make
Package pam was not found in the pkg-config search path.
Perhaps you should add the directory containing `pam.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pam' found
cc -std=c11 -Iinclude -DPREFIX=/usr  -DMAJOR_VERSION=2 -DMINOR_VERSION=0 -DMICRO_VERSION=0   -c -o src/auth.o src/auth.c
In file included from src/auth.c:15:
include/auth.h:8:10: fatal error: glib.h: No such file or directory
    8 | #include <glib.h>
      |          ^~~~~~~~
compilation terminated.
```

**Comment by jovanlanik** [comment]
Seems like you are missing pam.pc? Check if any package provides it.

**Comment by jovanlanik** [comment]
I updated the makefile so the error is obvious.

**Comment by kgilmer** [comment]
Thanks @jovanlanik .  That clears up the root cause of my problem.  It's odd that I cannot find a [debian package that provides `pam.pc`](https://packages.ubuntu.com/search?keywords=pam.pc&searchon=contents).  This can hardly be an edge case so I must be missing something obvious.  I'll keep digging.  In any case, thanks for your speedy help!

**Comment by kgilmer** [comment]
For whatever reason, Ubuntu 22.04 lacks a standard package that ships `pam.pc`.  A colleague of mine came up with a workaround to the issue [here](https://github.com/regolith-linux/gtklock/commit/a3f80fe7e337d7ad1ca9b90d111dbbb1401ca56c).  FYI we will likely be packaging `gtklock` for Debian and Ubuntu for use in Regolith in an upcoming version.  Happy to contribute to your readme for building for these targets if interested.
